### PR TITLE
Refactored the directive to be configurable

### PR DESCRIPTION
**Pull request by lifeisfoo**
- the `sendRequest` has been replaced with a promise passed via the configuration scope;
- `merchantId` and `environment` are configurable from the configuration scope;
- the module is now self contained and can be imported in your app module dependencies without changes;

### CODE REVIEW

**Comment by tyrw** [comment]
Thanks for your PR.  I'm not understanding your intent here:
- What is the benefit of factoring out the url as an input that requires a promise to be defined in an external controller?
- What is the benefit of placing the directive in an IIFE?

**Comment by lifeisfoo** [comment]
The benefit of the _url as promise_ is that usually you want to create a paypal payment only when the user want to pay (e.g. when he click on the button). The promise allows you:
- to have all the _url grabbing/manipulation code_ defined externally (separation of concerns). The module is reusable without change and every developer could have a different backend output;
- to call the server function that returns the url only when the button is clicked (like you do now); 

In my case, I have a json output from the server with the _url_ and other fields: with the external promise I can keep the module clean because both the $http call and the response manipulation that extract the url are defined externally (in the promise).

About the benefit of placing the directive in an IIFE you can read [angular-styleguide/iife](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#iife). Also, this will allows us to write the directive as a function and only bind the function name to the directive declaration. See [angular-styleguide/directives](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#directives) (but I didn't do it yet).

I hope my answer was clear.

**Comment by tyrw** [comment]
Thanks for clarifying 👍 

On the separation of concerns point, it's not clear to me why you'd want the server call for the url to be controller-specific, as I would imagine most apps will make the same call regardless of button placement.  In this case, it makes more sense (to me) for that to functionality to live inside the button itself.  If your app makes different url calls based on the controller within your app, then I agree it makes sense to factor as you have done, but I don't think this will be the most common use case.

On the IIFE point, the pattern is different here than in the styleguide you mentioned.  There is no pollution of the global namespace with named controller functions, and thus no need to encapsulate them.  Note that the code uses an anonymous function instead of a named one, which I see is against the styleguide's suggestion.

That said, if you want to submit a PR to bring in line with the styleguide and IIFE a la:

```
angular
    .module('paypal-checkout')
    .directive("paypalCheckout", paypalCheckout)

(...)()
```

Then I am happy to pull that in.  Thanks!

**Comment by lifeisfoo** [comment]
You're right when you say:

> as I would imagine most apps will make the same call regardless of button placement
> and, yes:
> If your app makes different url calls based on the controller within your app [...] I don't think this will be the most common use case
> My app, indeed, has only one url to call and only one controller that shows the button (this is a common use case, I think). And because the server call differs from app to app, it's a good point, at least for me, to have this logic out of the directive.

Moreover, the complete external configuration allows you to make a bower/npm module for this useful directive. In this way, anyone could add the paypal checkout without manually copying files :).

**Comment by tyrw** [comment]
I do appreciate your enthusiasm for this directive.  I think we have different coding preferences though :)

For me, this is a simple directive that is easy for anyone to understand and edit for their own needs.  The approach of refactoring outside of the directive makes perfect sense to me; I just think it is overkill for something so simple.  Adding a promise object to the input and increasing documentation both add complexity where I don't believe it is needed.

If you want to fork and take the promise + bower/npm approach, I think there will be people out there that prefer that way just as you do.  So if you want to do it, I won't complain 👍

**Comment by lifeisfoo** [comment]
Don't worry, I understand.
Just merge, if you want, the pieces of code that you think are useful to your directive, otherwise close directly this PR.

If I have time, I'll create a promise+bower/npm version of this directive. I'll mention the original repo in the documentation.

Thank you again for your work.

**Comment by tyrw** [comment]
Updated IIFE and directive declaration per style guide with https://github.com/twler/angular-paypal-checkout/commit/466f10e0dc7aab3e97e95024169f07738c780edc

Thanks for your help on this 👍

**Pull request closed without merging**
